name : On demand build

on:
    workflow_dispatch:
      inputs:
        branch-name:
          type: string
          required: true
        services:
          type: string
          required: true

jobs:
    publish:
        if: ${{ contains(github.event.inputs.services || '', 'threedsecure') }}
        uses: maheshaila01/env_secrets/.github/workflows/test.yml@main
        with: 
            branch-name: ${{ inputs.branch-name }}
            environment: "prod"
        secrets: inherit
