name : On demand build

on:
    workflow_dispatch:
        inputs:
            branch_name:
                type: string
                required: true


jobs:
    publish:
        uses: maheshaila01/actions_test/.github/workflows/secrets-passthrough.yml@main
        with: 
            branch_name: ${{ inputs.branch_name }}